name: dr_time
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5 
  image_picker: ^1.0.4
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/Icon/
    - assets/splash/

flutter_native_splash:
  fullscreen: true
  color: "#EEEEEE"
  image: assets/splash/drTimeSplash.png
  android_12:
    image: assets/splash/drTimeSplash.png
    color: "#EEEEEE"
    icon_background_color: "#EEEEEE"

flutter_launcher_icons:
  image_path: "assets/Icon/drtime.png"
  android: true
  ios: true
