// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }



  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp-QabFQhmPDNsXqt8vbEXG5MH41q-5o4',
    appId: '1:1081704102191:web:90bd1cd69a35b9efba89da',
    messagingSenderId: '1081704102191',
    projectId: 'jakop-5b0d2',
    storageBucket: 'jakop-5b0d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp-QabFQhmPDNsXqt8vbEXG5MH41q-5o4',
    appId: '1:1081704102191:android:90bd1cd69a35b9efba89da',
    messagingSenderId: '1081704102191',
    projectId: 'jakop-5b0d2',
    storageBucket: 'jakop-5b0d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlWMoU2gVBgEfIAckI2obBgw1xnlb4z2E',
    appId: '1:1081704102191:ios:410c3f1b7b2b8782ba89da',
    messagingSenderId: '1081704102191',
    projectId: 'jakop-5b0d2',
    storageBucket: 'jakop-5b0d2.firebasestorage.app',
    iosBundleId: 'com.example.drTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlWMoU2gVBgEfIAckI2obBgw1xnlb4z2E',
    appId: '1:1081704102191:ios:410c3f1b7b2b8782ba89da',
    messagingSenderId: '1081704102191',
    projectId: 'jakop-5b0d2',
    storageBucket: 'jakop-5b0d2.firebasestorage.app',
    iosBundleId: 'com.example.drTime',
  );


}
